# Generated by Django 4.0.1 on 2022-01-29 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
