version: '3.1'

services:
  postgres:
    image: postgres
    volumes:
      - ./pgdb/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080
