# Generated by Django 4.0.1 on 2022-01-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('link', models.CharField(blank=True, max_length=128, null=True)),
                ('heading', models.CharField(blank=True, max_length=128)),
                ('desc', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
