# Generated by Django 4.0.1 on 2022-02-24 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
