# Generated by Django 4.0.1 on 2022-02-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('count', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
    ]
