# Generated by Django 4.0.2 on 2022-02-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=225, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('desc', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
