# Generated by Django 4.0.2 on 2022-03-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_blog_desc_alter_testimonial_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='link',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
